server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5401/tracking_db
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
logging:
  level:
    io.ylab: INFO
springdoc:
  swagger-ui:
    tagsSorter: alpha
    operations-sorter: method

swagger:
  info:
    title: "API Tracking"
    description: "Backend сервис для приложения «WaterConsumptionTrackingApp»"
